### ISSUE TITLE
不同分辨率patch 特征如何获取？

### ISSUE THREAD

**Issue by CV-ZhangXin** [Hanminghao/MSCPT#7]
@Hanminghao 您好！
非常感谢你们的杰出工作，
我想问一下，下载TCGA-RCC数据集之后，怎么获得低分辨和高分辨率下的Patch特征呢？

**Comment by Hanminghao** [comment]
你好，我们使用了 [CLAM](https://github.com/mahmoodlab/CLAM) 进行patch 生成和特征提取，有些没有 5X 或 20X 的 WSI 切片，我们在大一级的分辨率上（10X 和 40X）进行裁切并 Resize 得到对应特征。

**Comment by CV-ZhangXin** [comment]
@Hanminghao 非常感谢你的回复，你的意思是能下栽到不同分辨率的WSI图像吗？我刚刚去了官网好像下载TCGA的数据集没有放大倍率这个选项。

**Comment by Hanminghao** [comment]
从 TCGA 下载的数据保存为金字塔结构，最大分辨率一般为 20X 或 40X，可以使用 openslide 来对不同分辨率下的图像进行操作。
